# Generated by Django 2.1.2 on 2019-09-30 15:40

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190929_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHECK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
            ],
        ),
    ]
