# Generated by Django 2.1.2 on 2019-09-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHECK',
        ),
    ]
