# Generated by Django 2.1.2 on 2019-10-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
