# Generated by Django 2.2.5 on 2019-10-31 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='id',
        ),
        migrations.AlterField(
            model_name='product_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Shop'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='sub_category',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
