# Generated by Django 2.2.5 on 2019-10-31 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20191031_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Shop',
            field=models.ForeignKey(default='all', on_delete=django.db.models.deletion.CASCADE, to='products.Shop'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Shop'),
        ),
    ]
